{
	"id":'0006',
	"time":'2020/12/26',
	"title":'如何对网站的文件和资源进行优化？',
	"question_type":'A',
	"zhaiyao":'对网站的文件资源进行优化（以网站的打开速度来作为参照），应该怎么来操作，所以我设计了这个实验',
	"img1_title":'提出问题',
	"main1":'对文件资源进行什么样的操作才能优化这个网站？',
	"img1":'',
	"beizhu1":'',
	"img2_title":'作出假设',
	"main2":'压缩文件资源应该能够优化这个网站',
	"img2":'',
	"beizhu2":'',
	"img3_title":'设计实验验证',
	"main3":'控制变量：同一个浏览器，同一个网络环境，同一个PC；对照组：在原来网站的基础上，对图片，CSS文件进行压缩过的网站，',
	"img3":'',
	"beizhu3":'',
	"img4_title":'得出结论',
	"main4":'压缩网站的文件资源确实能够优化网站',	
	"img4":'',
	"beizhu4":'',
},
{
	"id":'0005',
	"time":'2020/12/26',
	"title":'企业中项目流程概括',
	"type":'E',
	"head_info":'',
	"duanluo":[
		{
			"title":'项目需求分析',
			"main":'',	
			"img1_title1":'',
			"img1":'',
			"beizhu1":'';	
			"img1_title2":'',
			"img2":'',
			"beizhu2":'';				
		},
		{
			"title":'页面设计/项目选型',
			"main":'',
			"img":'',
			"beizhu1":'';	
			"img2":'',			
			"beizhu2":'';
		},
		{
			"title":'编码',
			"main":'',
			"img":'',
			"beizhu1":'';
			"img2":'',				
			"beizhu2":'';
		},
		{
			"title":'测试',
			"main":'',
			"img":'',
			"beizhu1":'';				
			"img2":'',
			"beizhu2":'';
		},
		{
			"title":'维护',
			"main":'',
			"img":'',
			"beizhu1":'';				
			"img2":'',
			"beizhu2":'';
		},
	],
	"link-down":'',
	"link-off":'',
	"link-from":'',
},